

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - AUTH_SECRET=${AUTH_SECRET}
        - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
        - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
        - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
        - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
        - UPSTASH_REDIS_TOKEN=${UPSTASH_REDIS_TOKEN}
        - QSTASH_URL=${QSTASH_URL}
        - QSTASH_TOKEN=${QSTASH_TOKEN}
        - RESEND_WORKFLOW=${RESEND_WORKFLOW}
        - NEXT_PROD_API_ENDPOINT=${NEXT_PROD_API_ENDPOINT}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped